name: Release a New Version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name to be used for this release.'
        required: true
        type: string
      prerelease:
        description: 'Whether this tag is a pre-release or not. Default to false'
        required: true
        type: boolean
  # push:
  #   tags:
  #     - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:

    - name: Consolidate variables
      run: |
        echo "Inputs: $REF_TYPE, $GITHUB_REF, $TAG"
        if [[ "$REF_TYPE" = "tag" ]]; then
          echo "Run via tag!"
          FINAL_TAG=$GITHUB_REF
        elif [[ ! -z "$TAG" ]]; then
          echo "Run via workflow dispatch, tag is supplied: $TAG"
          FINAL_TAG=$TAG
        else
          echo "Run via workflow dispatch, tag not supplied"
        fi

        if [[ "$PRERELEASE" = "true" ]]; then
          FINAL_TAG="$FINAL_TAG"-SNAPSHOT
        fi

        echo "FINAL_TAG=$FINAL_TAG" >> $GITHUB_ENV
      env:
        REF_TYPE: ${{ github.ref_type }}
        TAG: ${{ inputs.tag }}
        PRERELEASE: ${{ inputs.prerelease }}

    - name: Check out repository
      uses: actions/checkout@v7

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'oracle'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew test spotlessCheck build

    - name: Show output files
      run: |
        echo "$GITHUB_WORKSPACE, $FINAL_TAG" && \
        ls $GITHUB_WORKSPACE/fabric/build/libs/commandr-fabric-*-$FINAL_TAG.jar && \
        ls $GITHUB_WORKSPACE/forge/build/libs/commandr-forge-*-$FINAL_TAG.jar && \
        ls $GITHUB_WORKSPACE/neoforge/build/libs/commandr-neoforge-*-$FINAL_TAG.jar

    - name: Create Release
      uses: softprops/action-gh-release@v3
      with:
        name: ${{ env.FINAL_TAG }}
        tag_name: ${{ env.FINAL_TAG }}
        generate_release_notes: true
        prerelease: ${{ inputs.prerelease }}
        files: |
          fabric/build/libs/commandr-fabric-*-${{ env.FINAL_TAG }}.jar
          forge/build/libs/commandr-forge-*-${{ env.FINAL_TAG }}.jar
          neoforge/build/libs/commandr-neoforge-*-${{ env.FINAL_TAG }}.jar
        fail_on_unmatched_files: true
